zuul:
  routes:
    firm1:
      path: /firms/**
      serviceId: firm
      strip-prefix: false
    firm2:
      path: /engines/**
      serviceId: firm
      strip-prefix: false
#    firm3:
#      path: /hello.xhtml
#      serviceId: firm
#      strip-prefix: false
#    firm4:
#      path: /engine_firms_profile.xhtml
#      serviceId: firm
#      strip-prefix: false
#    firm5:
#      path: /firms_control.xhtml
#      serviceId: human
#      strip-prefix: false
#    firm6:
#      path: /weapon_firms_profile.xhtml
#      serviceId: firm
#      strip-prefix: false
#    firm7:
#      path: /universal_firms_profile.xhtml
#      serviceId: firm
#      strip-prefix: false
#    firm8:
#      path: /firm_reg.xhtml
#      serviceId: firm
#      strip-prefix: false
#    tank1:
#      path: /amun.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank5:
#      path: /adding_tank_details.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank2:
#      path: /link_tank_detailsMtM.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank3:
#      path: /moderator_page.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank4:
#      path: /show_tank_avallable_details.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank6:
#      path: /tanks_manipulations.xhtml
#      serviceId: tank
#      strip-prefix: false
#    tank7:
#      path: /start.xhtml
#      serviceId: tank
#      strip-prefix: false
#    human1:
#      path: /human_control.xhtml
#      serviceId: human
#      strip-prefix: false
#    human2:
#      path: /hello_human.xhtml
#      serviceId: human
#      strip-prefix: false
#    human3:
#      path: /human_reg.xhtml
#      serviceId: human
#      strip-prefix: false
    human4:
      path: /humans/**
      serviceId: human
      strip-prefix: false
#    human5:
#      path: /human_profile.xhtml
#      serviceId: human
#      strip-prefix: false